#!/usr/bin/env python3
"""
generate_docs.py
================
Automated API documentation generator for the CRM Order Management API.

Reads the OpenAPI 3.0 specification at docs/openapi/v1/openapi.yaml and
generates a complete Markdown reference page at docs/generated-api-doc.md.

This script is designed to be run:
  - Locally:  python scripts/generate_docs.py
  - In CI/CD: automatically as part of the GitHub Actions build pipeline

The output document covers:
  - API overview and base URL
  - Authentication
  - Parameter reference table
  - All endpoints (dynamically from spec paths – no hardcoding)
  - Request/response examples
  - Error responses per endpoint
  - HTTP status codes reference
"""

import json
import sys
import yaml
from pathlib import Path
from datetime import datetime, timezone

# ── Paths ─────────────────────────────────────────────────────────────────────

SPEC_PATH = Path("docs/openapi/v1/openapi.yaml")
OUTPUT_PATH = Path("docs/generated-api-doc.md")

# ── Helpers ───────────────────────────────────────────────────────────────────

def fmt_json(data: dict) -> str:
    """Return pretty-printed JSON string."""
    return json.dumps(data, indent=2)

def get_example(content: dict | None) -> dict | None:
    """Extract the first application/json example from a content block."""
    if not content:
        return None
    return content.get("application/json", {}).get("example")

def resolve_ref(spec: dict, ref: str) -> dict:
    """Resolve a $ref string like '#/components/schemas/Order' to its definition."""
    if not ref.startswith("#/"):
        return {}
    parts = ref.lstrip("#/").split("/")
    node = spec
    for part in parts:
        node = node.get(part, {})
    return node

def get_response_example(spec: dict, response: dict) -> dict | None:
    """Extract example from a response, resolving $ref if needed."""
    if "$ref" in response:
        response = resolve_ref(spec, response["$ref"])
    content = response.get("content")
    return get_example(content)

def type_label(prop: dict) -> str:
    """Return a formatted type label for a schema property."""
    t = prop.get("type", "string")
    fmt = prop.get("format")
    if fmt:
        return f"`{t}` ({fmt})"
    return f"`{t}`"

def method_badge(method: str) -> str:
    """Return an uppercase HTTP method label."""
    return method.upper()

# ── Section builders ──────────────────────────────────────────────────────────

def build_header(api: dict) -> str:
    info = api.get("info", {})
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# {info.get('title', 'API Reference')}",
        "",
        f"> **Auto-generated** from `docs/openapi/v1/openapi.yaml` on {now}.",
        "> Do not edit this file directly – update the OpenAPI spec and re-run `generate_docs.py`.",
        "",
        f"{info.get('description', '').strip()}",
        "",
    ]
    return "\n".join(lines)

def build_servers(api: dict) -> str:
    servers = api.get("servers", [])
    if not servers:
        return ""
    lines = ["## Base URLs", ""]
    for s in servers:
        desc = s.get("description", "")
        lines.append(f"- `{s['url']}` – {desc}")
    lines.append("")
    return "\n".join(lines)

def build_auth(api: dict) -> str:
    schemes = api.get("components", {}).get("securitySchemes", {})
    if not schemes:
        return ""
    lines = ["## Authentication", ""]
    for name, scheme in schemes.items():
        scheme_type = scheme.get("type", "")
        if scheme_type == "apiKey":
            location = scheme.get("in", "header")
            key_name = scheme.get("name", "")
            lines.append(f"**Type:** API Key  ")
            lines.append(f"**Header:** `{key_name}` (in `{location}`)  ")
            lines.append(f"**Description:** {scheme.get('description', '')}  ")
        lines.append("")
    lines.append("**Example:**")
    lines.append("")
    lines.append("```bash")
    key_name = next(
        (s.get("name") for s in schemes.values() if s.get("type") == "apiKey"),
        "X-API-Key",
    )
    lines.append(f'curl -H "{key_name}: your-api-key" https://api.example.com/v1/orders')
    lines.append("```")
    lines.append("")
    return "\n".join(lines)

def build_parameters_table(api: dict) -> str:
    """Build a parameter reference table from the main Order schema."""
    schemas = api.get("components", {}).get("schemas", {})
    order_schema = schemas.get("Order", {})
    properties = order_schema.get("properties", {})
    required_fields = order_schema.get("required", [])

    if not properties:
        return ""

    lines = [
        "## Parameter Reference",
        "",
        "The following table lists all fields used in the Order Management API.",
        "",
        "| Parameter | Type | Description | Required |",
        "| --- | --- | --- | --- |",
    ]

    for field, prop in properties.items():
        t = type_label(prop)
        desc = prop.get("description", "–")
        if field == "orderId":
            req = "Yes (for specific operations)"
        elif field in required_fields:
            req = "Yes"
        elif field in ("createdAt", "updatedAt"):
            req = "No (system-set)"
        else:
            req = "No"
        lines.append(f"| `{field}` | {t} | {desc} | {req} |")

    lines.append("")
    return "\n".join(lines)


def build_endpoint(spec: dict, method: str, path: str, operation: dict) -> str:
    """Build a full Markdown section for a single endpoint."""
    summary = operation.get("summary", path)
    description = operation.get("description", "").strip()
    operation_id = operation.get("operationId", "")

    lines = [
        f"### {method_badge(method)} {path}",
        "",
        f"**Summary:** {summary}",
        "",
    ]

    if description:
        lines += [description, ""]

    if operation_id:
        lines += [f"**Operation ID:** `{operation_id}`", ""]

    # Path + Query parameters
    params = operation.get("parameters", [])
    if params:
        # Resolve $ref parameters
        resolved_params = []
        for p in params:
            if "$ref" in p:
                resolved_params.append(resolve_ref(spec, p["$ref"]))
            else:
                resolved_params.append(p)

        path_params = [p for p in resolved_params if p.get("in") == "path"]
        query_params = [p for p in resolved_params if p.get("in") == "query"]

        if path_params:
            lines += ["**Path Parameters:**", ""]
            lines += ["| Parameter | Type | Required | Description |",
                      "| --- | --- | --- | --- |"]
            for p in path_params:
                t = type_label(p.get("schema", {}))
                req = "Yes" if p.get("required") else "No"
                desc = p.get("description", "–")
                lines.append(f"| `{p['name']}` | {t} | {req} | {desc} |")
            lines.append("")

        if query_params:
            lines += ["**Query Parameters:**", ""]
            lines += ["| Parameter | Type | Required | Default | Description |",
                      "| --- | --- | --- | --- | --- |"]
            for p in query_params:
                schema = p.get("schema", {})
                t = type_label(schema)
                req = "Yes" if p.get("required") else "No"
                default = str(schema.get("default", "–"))
                desc = p.get("description", "–")
                lines.append(f"| `{p['name']}` | {t} | {req} | `{default}` | {desc} |")
            lines.append("")

    # Request body
    request_body = operation.get("requestBody")
    if request_body:
        req_example = get_example(request_body.get("content"))
        if req_example:
            lines += ["**Request Body:**", "", "```json", fmt_json(req_example), "```", ""]

    # Responses
    responses = operation.get("responses", {})
    success_codes = [c for c in responses if str(c).startswith("2")]
    error_codes = [c for c in responses if not str(c).startswith("2")]

    # Success responses
    for code in sorted(success_codes):
        response = responses[code]
        if "$ref" in response:
            response = resolve_ref(spec, response["$ref"])
        desc = response.get("description", "")
        example = get_response_example(spec, responses[code])
        lines.append(f"**Response – {code} {desc}:**")
        lines.append("")
        if example:
            lines += ["```json", fmt_json(example), "```", ""]
        else:
            lines += [f"_{desc}. No response body._", ""]

    # Error responses
    if error_codes:
        lines += ["**Error Responses:**", ""]
        for code in sorted(error_codes):
            response = responses[code]
            if "$ref" in response:
                response = resolve_ref(spec, response["$ref"])
            desc = response.get("description", "")
            example = get_response_example(spec, responses[code])
            lines.append(f"_{code} {desc}_")
            lines.append("")
            if example:
                lines += ["```json", fmt_json(example), "```", ""]

    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def build_endpoints_section(spec: dict) -> str:
    paths = spec.get("paths", {})
    method_order = ["post", "get", "put", "patch", "delete"]

    lines = ["## Endpoints", ""]

    # Summary table
    lines += ["| Method | Endpoint | Summary |", "| --- | --- | --- |"]
    for path, path_item in paths.items():
        for method in method_order:
            if method in path_item:
                op = path_item[method]
                lines.append(f"| `{method.upper()}` | `{path}` | {op.get('summary', '')} |")
    lines += ["", "---", ""]

    # Full endpoint sections
    for path, path_item in paths.items():
        for method in method_order:
            if method in path_item:
                lines.append(build_endpoint(spec, method, path, path_item[method]))

    return "\n".join(lines)


def build_status_codes() -> str:
    return """\
## HTTP Status Codes

| Code | Meaning | Description |
| --- | --- | --- |
| `200` | OK | Successful GET or PUT. |
| `201` | Created | Resource created successfully via POST. |
| `204` | No Content | Resource deleted successfully via DELETE. |
| `400` | Bad Request | Missing required fields or invalid values. |
| `401` | Unauthorized | API key is missing, invalid, or revoked. |
| `404` | Not Found | The specified resource does not exist. |
| `409` | Conflict | Operation not allowed in the resource's current state. |
| `429` | Too Many Requests | Rate limit exceeded. Retry after 60 seconds. |
| `500` | Internal Server Error | Unexpected server error. Contact support. |
"""

# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    if not SPEC_PATH.exists():
        print(f"❌ OpenAPI spec not found at {SPEC_PATH}", file=sys.stderr)
        sys.exit(1)

    with SPEC_PATH.open("r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)

    sections = [
        build_header(spec),
        build_servers(spec),
        build_auth(spec),
        build_parameters_table(spec),
        build_endpoints_section(spec),
        build_status_codes(),
    ]

    output = "\n".join(sections)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        f.write(output)

    print(f"✅ Documentation generated → {OUTPUT_PATH}")
    print(f"   Endpoints documented: {sum(1 for p in spec.get('paths', {}).values() for m in ['get','post','put','patch','delete'] if m in p)}")

if __name__ == "__main__":
    main()
